version: '3'

services:
  db:
    container_name: ruby-project-example-db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /tmp/db:/var/lib/postgresql/data

  app:
    container_name: ruby-project-example-app
    build: .
    depends_on:
      - db
    volumes:
      - .:/ruby-project-example
